name: Deploy cyf-cloud.front

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pull and rebuild
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /home/cyf/.web/cyf-cloud.front
          git pull
          cnpm install
          npm run build