name: Deploy cyf-cloud.front

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Pull and rebuild
      uses: appleboy/ssh-action@master
      with:
        host: se.cyf-cloud.cn
        username: cyf
        password: ${{ secrets.PSWD }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          cd /home/cyf/.web/cyf-cloud.front
          git pull
          cnpm install
          npm run build